name: Auto Pull Request with Reviewer and Assignee

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto PR: ${{ github.ref_name }} -> main'
          base: main
          body: |
            This pull request was automatically created from a push to `${{ github.ref_name }}`.
          reviewers: |
            ankurtrivedi2001
          assignees: |
            ankurtrivedi2001
            navi098
