name: Production Deployment

on: 
  push:
    branches:
      - main
    paths:
      - force-app/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Initializing Workflow
        uses: actions/checkout@v2

      - name: Setting up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.0.0'

      - name: Installing Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authorize Production
        run: |
          echo "Salesforce authorization running"
          sfdx auth:sfdxurl:store --sfdx-url-file <(echo "${{ secrets.SF_PROD_AUTH_URL }}") --set-default --alias Prod

      - name: Validate Metadata in Production
        run: |
          echo "Validating metadata in production with specific test class..."
          sfdx force:source:deploy -p force-app \
            --checkonly \
            --testlevel RunSpecifiedTests \
            --runtests TestClassTest \
            --targetusername Prod

      - name: Deploy Metadata to Production
        run: |
          echo "Deploying metadata to production with specific test class..."
          sfdx force:source:deploy -p force-app \
            --testlevel RunSpecifiedTests \
            --runtests TestClassTest \
            --targetusername Prod
