name: Production Deployment

on: 
    commit:
        branches: main
        paths:
            - force-app/**
    jobs:
        test:
            runs-on: ubuntu-latest
            
            
     steps:
        - name: Initializing Workflow
        uses: actions/checkout@v2
        
        - name: Setting up SF CLI
         uses: actions/setup-node@v2
         with:
            node-version: 20.0.0

         - name: Installing SF
          run: npm install -g sfdx-cli
