name: Production Deployment

on: 
  push:
    branches:
      - main
    paths:
      - force-app/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Initializing Workflow
        uses: actions/checkout@v2

      - name: Setting up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.0.0'

      - name: Installing Salesforce CLI
        run: npm install -g sfdx-cli
      
      - name: Authorize Production
      run: |
        echo "Salsforce authorization runnning"
        sfdx org login sfdx-url --set default --sfdx-url-file <(echo "${{secrets.SF_PROD_AUTH_URL}}")

